# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Point explicitly to Eclipse Temurin OpenJDK 17 LTS (complete JDK with jlink)
org.gradle.java.home=C\:\\Users\\shash\\.antigravity\\extensions\\redhat.java-1.12.0-win32-x64\\jre\\17.0.4.1-win32-x86_64

# AndroidX package structure
android.useAndroidX=true
android.nonTransitiveRClass=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
